---
title: "Homework 1"
author: "Dylan Zumar"
date: "02/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Task 1

```{r mh_distance_function}
mh_distance <- function(x, y) {
  #Check NA, NaN, Inf, -Inf
  if (is.na(x) | is.na(y) | is.nan(x) | is.nan(y) | is.infinite(x)
      | is.infinite(y)) {
    warning("x or y is NA, NaN, Inf, or -Inf")
    return(-1)
  }
  #Check decimals
  if (is.numeric(x) && (round(x) != x)) {
    warning("x and/or y is a decimal")
    return(-1)
  }
  if (is.numeric(y) && (round(y) != y)) {
    warning("y is a decimal")
    return(-1)
  }
  #Check logical, numeric, character
  if (typeof(x) != typeof(y)) {
    warning("x and y are different types")
    return(-1)
  }
  if (!is.logical(x) & !is.numeric(x) & !is.character(x)) {
    warning("x is not logical, numeric, or character")
    return(-1)
  }
  if (!is.logical(y) & !is.numeric(y) & !is.character(y)) {
    warning("y is not logical, numeric, or character")
    return(-1)
  }
  #Check lengths
  if (is.numeric(x) & is.numeric(y)) {
    if (nchar(abs(x)) != nchar(abs(y))) {
      warning("x and y have different lengths")
        return(-1)
    }
  }
  if (is.character(x) & is.character(y)) {
    if (nchar(x) != nchar(y)) {
      warning("x and y have different lengths")
      return(-1)
    }
  }
  #Return logicals
  if (is.logical(x) & is.logical(y)) {
    if (x != y) {
      return(1)
    }
    else {
      return(0)
    }
  }
  #Return numeric and characters
  if (is.numeric(x) & is.numeric(y)) {
    a <- strsplit(as.character(abs(x)), split = "")[[1]]
    b <- strsplit(as.character(abs(y)), split = "")[[1]]
  }
  if (is.character(x) & is.character(y)) {
    a <- strsplit(as.character(x), split = "")[[1]]
    b <- strsplit(as.character(y), split = "")[[1]]
  }
  hamming <- 0
  for (i in 1:length(a)) {
    if (a[i] != b[i]) {
      hamming <- hamming + 1
    }
  }
  hamming
}
```


## Task 2

**Initial test cases** (return a non-negative modified Hamming distance)

```{r initial-test-cases}
mh_distance(x = "abc", y = "abc")
mh_distance(x = T, y = FALSE)
mh_distance(x = "523890", y = "752839")
mh_distance(x = 2341, y = 2350)
```

Added test cases that return a non-negative modified Hamming distance result.

```{r additional-test-cases-non-negative}
#Test all logicals
mh_distance(x = T, y = F) #1
mh_distance(x = T, y = T) #0
mh_distance(x = F, y = F) #0
mh_distance(x = TRUE, y = FALSE) #1
mh_distance(x = TRUE, y = TRUE) #0
mh_distance(x = FALSE, y = FALSE) #0

#Test numerics
mh_distance(5010,1050) #2
mh_distance(-456,456) #0
mh_distance(456,-456) #0
mh_distance(-456,-456) #0
mh_distance(5901,5911) #1
mh_distance(11578,12241) #4
mh_distance(300000,400000) #1
mh_distance(2.0,3.0) #1
mh_distance(2,3.0) #1
mh_distance(2.0,3) #1

#Test characters
mh_distance("right", "fight") #1
mh_distance("stop", "seek") #3
mh_distance("ABBA", "abba") #4
mh_distance("hi mom", "hi dad") #3
mh_distance("manna", "annam") #4
mh_distance("mom hi", "hi mom") #6
mh_distance("buffalo chicken sandwich", "bufgalo chicgen sangwich") #3
```

**Initial test cases** (return values of `-1`)

```{r eval=FALSE}
mh_distance(x = 52, y = 113)
mh_distance(x = "swimming", y = "winning")
mh_distance(x = NA, y = TRUE)
mh_distance(x = 1.5, y = 2.5)
```

Added test cases that return a value of `-1`.

```{r additional-test-cases-negative-one}
#Test all logicals
mh_distance(NA,T) #NA error
mh_distance(T,NA) #NA error
mh_distance(NA,F) #NA error
mh_distance(F,NA) #NA error
mh_distance(NA,TRUE) #NA error
mh_distance(TRUE,NA) #NA error
mh_distance(NA,FALSE) #NA error
mh_distance(FALSE,NA) #NA error
mh_distance(NaN,T) #NAn error
mh_distance(T,NaN) #NAn error
mh_distance(NaN,F) #NAn error
mh_distance(F,NaN) #NAn error
mh_distance(NaN,TRUE) #NAn error
mh_distance(TRUE,NaN) #NAn error
mh_distance(NaN,FALSE) #NAn error
mh_distance(FALSE,NaN) #NAn error
mh_distance(-Inf,T) #-Inf error
mh_distance(T,-Inf) #-Inf error
mh_distance(-Inf,F) #-Inf error
mh_distance(F,-Inf) #-Inf error
mh_distance(-Inf,TRUE) #-Inf error
mh_distance(TRUE,-Inf) #-Inf error
mh_distance(-Inf,FALSE) #-Inf error
mh_distance(FALSE,-Inf) #-Inf error
mh_distance(Inf,T) #Inf error
mh_distance(T,Inf) #Inf error
mh_distance(Inf,F) #Inf error
mh_distance(F,Inf) #Inf error
mh_distance(Inf,TRUE) #Inf error
mh_distance(TRUE,Inf) #Inf error
mh_distance(Inf,FALSE) #Inf error
mh_distance(FALSE,Inf) #Inf error

#Test numerics
mh_distance(x = -152, y = -49) #different lengths
mh_distance(x = 152, y = -49) #different lengths
mh_distance(x = -152, y = 49) #different lengths
mh_distance(-152.1, 152) #decimal error
mh_distance(-152, 152.1) #decimal error
mh_distance(-152.1, 152.1) #decimal error
mh_distance(152.1, 152) #decimal error
mh_distance(152, 152.1) #decimal error
mh_distance(152.1, 152.1) #decimal error
mh_distance(Inf,152) #Inf error
mh_distance(152,Inf) #Inf error
mh_distance(Inf,152) #Inf error
mh_distance(152,Inf) #Inf error
mh_distance(Inf,152) #Inf error
mh_distance(152,Inf) #Inf error
mh_distance(Inf,152.0) #Inf error
mh_distance(152,Inf) #Inf error
mh_distance(NA,152) #NA error
mh_distance(152,NA) #NA error
mh_distance(NA,152) #NA error
mh_distance(152,NA) #NA error
mh_distance(NA,152.0) #NA error
mh_distance(152,NA) #NA error
mh_distance(NA,152) #NA error
mh_distance(152,NA) #NA error
mh_distance(NaN,152) #NaN error
mh_distance(152.0,NaN) #NaN error
mh_distance(NaN,152) #NaN error
mh_distance(152,NaN) #NaN error
mh_distance(NaN,152) #NaN error
mh_distance(152,NaN) #NaN error
mh_distance(NaN,152) #NaN error
mh_distance(152,NaN) #NaN error
mh_distance(-Inf,152) #-Inf error
mh_distance(152,-Inf) #-Inf error
mh_distance(-Inf,152) #-Inf error
mh_distance(152,-Inf) #-Inf error
mh_distance(-Inf,152) #-Inf error
mh_distance(152,-Inf) #-Inf error
mh_distance(-Inf,152.0) #-Inf error
mh_distance(152,-Inf) #-Inf error

#Test strings
mh_distance("mom", "momi") #different lengths
mh_distance(Inf,"hi") #Inf error
mh_distance("hi",Inf) #Inf error
mh_distance(Inf,"hi") #Inf error
mh_distance("hi",Inf) #Inf error
mh_distance(Inf,"hi") #Inf error
mh_distance("hi",Inf) #Inf error
mh_distance(Inf,"hi") #Inf error
mh_distance("hi",Inf) #Inf error
mh_distance(NA,"hi") #NA error
mh_distance("hi",NA) #NA error
mh_distance(NA,"hi") #NA error
mh_distance("hi",NA) #NA error
mh_distance(NA,"hi") #NA error
mh_distance("hi",NA) #NA error
mh_distance(NA,"hi") #NA error
mh_distance("hi",NA) #NA error
mh_distance(NaN,"hi") #NaN error
mh_distance("hi",NaN) #NaN error
mh_distance(NaN,"hi") #NaN error
mh_distance("hi",NaN) #NaN error
mh_distance(NaN,"hi") #NaN error
mh_distance("hi",NaN) #NaN error
mh_distance(NaN,"hi") #NaN error
mh_distance("hi",NaN) #NaN error
mh_distance(-Inf,"hi") #-Inf error
mh_distance("hi",-Inf) #-Inf error
mh_distance(-Inf,"hi") #-Inf error
mh_distance("hi",-Inf) #-Inf error
mh_distance(-Inf,"hi") #-Inf error
mh_distance("hi",-Inf) #-Inf error
mh_distance(-Inf,"hi") #-Inf error
mh_distance("hi",-Inf) #-Inf error
```


## Task 3

Consider the pair of vectors `s` and `w` given below.

```{r}
s <- c(26, 50123, 456.12, 8, 0)
w <- c(22, 50000, 451.00, 88, 0)
```

```{r}
# loop goes here
```


## Task 4

Brief write-up goes here...
